/**
 * Panel styles. Scoped by the plugin's own data attributes and .rrp- class
 * prefixes so nothing leaks into the rest of the GUI; colors ride the dsh
 * --dsw-* tokens so the panel follows the active theme. The center-column
 * takeover rules are attribute-scoped and must stay in this stylesheet.
 */
export const STYLES_CSS = [
  "/* center-column takeover (attribute-scoped, mirrors the ssh panel) */",
  "[data-pane='conversation'] { position: relative; }",
  "[data-dsh-record-replay-view] { position: absolute; inset: 0; display: none; z-index: 60; background: var(--dsw-alias-bg-base, #fff); overflow: hidden; }",
  "html[data-dsh-record-replay-active]:not([data-dsh-taskboard-active]):not([data-dsh-ssh-active]) [data-dsh-record-replay-view] { display: flex; flex-direction: column; }",
  "html[data-dsh-record-replay-active]:not([data-dsh-taskboard-active]):not([data-dsh-ssh-active]) [data-pane='conversation'] > :not([data-dsh-record-replay-view]),",
  "html[data-dsh-record-replay-active]:not([data-dsh-taskboard-active]):not([data-dsh-ssh-active]) [class*='centerCol'] > :not([data-dsh-record-replay-view]) { display: none !important; }",
  "",
  "/* sidebar entry row */",
  ".rrp-entry { display: flex; align-items: center; gap: 8px; width: 100%; height: 32px; padding: 0 12px; background: transparent; border: none; border-radius: 8px; color: var(--dsw-alias-label-secondary); cursor: pointer; font-size: 13px; white-space: nowrap; }",
  ".rrp-entry:hover { background: var(--dsw-specific-sidebar-nav-item-hover); color: var(--dsw-alias-label-primary); }",
  ".rrp-entry[data-active] { background: var(--dsw-specific-sidebar-nav-item-active); color: var(--dsw-alias-label-primary); font-weight: 600; }",
  ".rrp-entryIcon { display: inline-flex; align-items: center; justify-content: center; }",
  ".rrp-entryLabel { flex: 1; text-align: left; overflow: hidden; text-overflow: ellipsis; }",
  "",
  "/* panel shell */",
  ".rrp-root { display: flex; flex-direction: column; height: 100%; min-height: 0; }",
  ".rrp-header { display: flex; align-items: center; gap: 8px; padding: 12px 16px; border-bottom: 1px solid var(--dsw-alias-divider, rgba(128,128,128,0.2)); }",
  ".rrp-headerTitle { font-size: 15px; font-weight: 600; color: var(--dsw-alias-label-primary); flex: 1; }",
  ".rrp-tabs { display: flex; gap: 4px; padding: 8px 16px 0; border-bottom: 1px solid var(--dsw-alias-divider, rgba(128,128,128,0.2)); }",
  ".rrp-tab { padding: 6px 14px; border: none; background: transparent; border-radius: 8px 8px 0 0; color: var(--dsw-alias-label-secondary); cursor: pointer; font-size: 13px; }",
  ".rrp-tab[data-active] { color: var(--dsw-alias-label-primary); font-weight: 600; background: var(--dsw-specific-sidebar-nav-item-active, rgba(128,128,128,0.12)); }",
  ".rrp-body { flex: 1; min-height: 0; overflow: auto; padding: 12px 16px; }",
  "",
  "/* buttons */",
  ".rrp-btn { padding: 4px 10px; border: 1px solid var(--dsw-alias-divider, rgba(128,128,128,0.3)); border-radius: 6px; background: transparent; color: var(--dsw-alias-label-secondary); cursor: pointer; font-size: 12px; }",
  ".rrp-btn:hover { background: var(--dsw-specific-sidebar-nav-item-hover, rgba(128,128,128,0.08)); color: var(--dsw-alias-label-primary); }",
  ".rrp-btn[data-primary] { background: var(--dsw-specific-accent, #4f6ef2); border-color: transparent; color: #fff; }",
  ".rrp-btn[data-danger]:hover { border-color: rgba(220,60,60,0.5); color: #dc3c3c; }",
  ".rrp-btn:disabled { opacity: 0.5; cursor: default; }",
  "",
  "/* session / pack rows */",
  ".rrp-list { display: flex; flex-direction: column; gap: 8px; }",
  ".rrp-row { display: flex; align-items: center; gap: 10px; padding: 10px 12px; border: 1px solid var(--dsw-alias-divider, rgba(128,128,128,0.2)); border-radius: 10px; }",
  ".rrp-rowMain { flex: 1; min-width: 0; }",
  ".rrp-rowTitle { font-size: 13px; font-weight: 600; color: var(--dsw-alias-label-primary); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }",
  ".rrp-rowMeta { font-size: 11px; color: var(--dsw-alias-label-secondary); margin-top: 2px; }",
  ".rrp-rowActions { display: flex; gap: 6px; }",
  ".rrp-empty { color: var(--dsw-alias-label-secondary); font-size: 13px; line-height: 1.6; padding: 24px 8px; }",
  ".rrp-error { color: #dc3c3c; font-size: 13px; padding: 12px; }",
  "",
  "/* viewer */",
  ".rrp-viewer { display: flex; flex-direction: column; height: 100%; min-height: 0; }",
  ".rrp-viewerToolbar { display: flex; align-items: center; gap: 8px; padding: 8px 16px; border-bottom: 1px solid var(--dsw-alias-divider, rgba(128,128,128,0.2)); }",
  ".rrp-viewerSearch { flex: 1; max-width: 320px; padding: 5px 10px; border: 1px solid var(--dsw-alias-divider, rgba(128,128,128,0.3)); border-radius: 6px; background: transparent; color: var(--dsw-alias-label-primary); font-size: 12px; }",
  ".rrp-viewerStats { font-size: 11px; color: var(--dsw-alias-label-secondary); }",
  ".rrp-timeline { flex: 1; min-height: 0; overflow: auto; padding: 12px 16px 40px; display: flex; flex-direction: column; gap: 10px; }",
  ".rrp-item { border-radius: 10px; padding: 10px 12px; font-size: 13px; line-height: 1.6; }",
  ".rrp-item-user { align-self: flex-end; max-width: 85%; background: var(--dsw-specific-accent, #4f6ef2); color: #fff; white-space: pre-wrap; word-break: break-word; }",
  ".rrp-item-assistant { align-self: stretch; background: var(--dsw-alias-bg-elevated, rgba(128,128,128,0.06)); color: var(--dsw-alias-label-primary); white-space: pre-wrap; word-break: break-word; }",
  ".rrp-item-tool, .rrp-item-result { align-self: stretch; background: rgba(128,128,128,0.07); border: 1px solid var(--dsw-alias-divider, rgba(128,128,128,0.2)); }",
  ".rrp-itemTag { display: inline-flex; align-items: center; gap: 6px; font-size: 11px; font-weight: 600; color: var(--dsw-alias-label-secondary); margin-bottom: 4px; }",
  ".rrp-itemTag code { background: rgba(128,128,128,0.15); padding: 1px 6px; border-radius: 4px; font-size: 11px; }",
  ".rrp-pre { margin: 0; font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12px; white-space: pre-wrap; word-break: break-word; max-height: 320px; overflow: auto; color: var(--dsw-alias-label-primary); }",
  ".rrp-details { margin-top: 4px; }",
  ".rrp-details summary { cursor: pointer; font-size: 12px; color: var(--dsw-alias-label-secondary); }",
  ".rrp-muted { color: var(--dsw-alias-label-secondary); }",
  ".rrp-turnDivider { display: flex; align-items: center; gap: 10px; font-size: 11px; color: var(--dsw-alias-label-secondary); margin-top: 6px; }",
  ".rrp-turnDivider::before, .rrp-turnDivider::after { content: ''; flex: 1; height: 1px; background: var(--dsw-alias-divider, rgba(128,128,128,0.2)); }",
  "",
  "/* run modal */",
  ".rrp-modalBackdrop { position: absolute; inset: 0; z-index: 80; background: rgba(0,0,0,0.35); display: flex; align-items: center; justify-content: center; }",
  ".rrp-modal { width: min(520px, 90%); max-height: 80%; background: var(--dsw-alias-bg-base, #fff); border-radius: 12px; box-shadow: 0 8px 40px rgba(0,0,0,0.25); display: flex; flex-direction: column; padding: 16px; gap: 12px; }",
  ".rrp-modalTitle { font-size: 15px; font-weight: 600; color: var(--dsw-alias-label-primary); }",
  ".rrp-modalBody { font-size: 13px; color: var(--dsw-alias-label-primary); line-height: 1.6; }",
  ".rrp-modalActions { display: flex; gap: 8px; justify-content: flex-end; }",
  "",
  "/* record tab */",
  ".rrp-recordBar { display: flex; align-items: center; gap: 10px; padding: 12px; border: 1px dashed var(--dsw-alias-divider, rgba(128,128,128,0.3)); border-radius: 10px; margin-bottom: 12px; flex-wrap: wrap; }",
  ".rrp-recordBtn { display: inline-flex; align-items: center; gap: 8px; padding: 8px 16px; border-radius: 8px; border: none; cursor: pointer; font-size: 13px; font-weight: 600; color: #fff; background: #dc3c3c; }",
  ".rrp-recordBtn:hover { filter: brightness(1.1); }",
  ".rrp-recordBtn:disabled { opacity: 0.5; cursor: default; }",
  ".rrp-recordBtn[data-primary] { background: var(--dsw-specific-accent, #4f6ef2); }",
  ".rrp-recordLive { display: inline-flex; align-items: center; gap: 6px; font-size: 12px; color: #dc3c3c; font-weight: 600; }",
  ".rrp-recordLive::before { content: ''; width: 8px; height: 8px; border-radius: 50%; background: #dc3c3c; animation: rrp-pulse 1.2s infinite; }",
  "@keyframes rrp-pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.25; } }",
  ".rrp-recordTimer { font-size: 12px; color: var(--dsw-alias-label-secondary); font-variant-numeric: tabular-nums; }",
  ".rrp-recordVideo { width: 100%; max-height: 240px; border-radius: 8px; background: #000; }",
  ".rrp-recordFrames { font-size: 12px; color: var(--dsw-alias-label-secondary); }",
].join('\n')